version: 1
root:
  handlers: ["stdout", "file"]
  level: DEBUG
loggers:
  "apscheduler.scheduler":
    level: WARN
  "apscheduler.executors.default":
    level: WARN
handlers:
  stdout:
    formatter: standard
    class: logging.StreamHandler
    level: DEBUG
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: standard
    filename: /smart-home-services/logs/output.log
    maxBytes: 1024000
    backupCount: 3
formatters:
  standard:
    format: "%(levelname)-8s | %(asctime)s | %(threadName)-25s | %(name)s: %(message)s"
